name: ESC
favicon: null
layout_spectrum: 0.01255
typography_spectrum: 0.5473
title: Efficiency Support Center
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4003c'
    - '#f6b2a2'
    - '#ec6d68'
    - '#f5f5f5'
    - '#e9547b'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
