title: Efficiency Support Center
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5878136
  brandStrength: 0.5
  lightness: 0.4982079
  brandColors:
    - '#0E0E0E'
    - '#FFFFFF'
    - '#B5BEC5'
    - '#888A8F'
    - '#5B5B5B'
  rhythmicContrast: 0.7849463
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: ESC
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5473
layout_spectrum: 0.01255
