name: ESC
favicon: null
layout_spectrum: 0.01255
typography_spectrum: 0.5473
title: Efficiency Support Center
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e90047'
    - '#f4f3f3'
    - '#ed2d67'
    - '#f2c7d4'
    - '#f095b0'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
