name: ESC
favicon: null
layout_spectrum: 0.74614
typography_spectrum: 0.5473
title: Efficiency Support Center
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e90047'
    - '#f4f3f3'
    - '#ed2d67'
    - '#f2c7d4'
    - '#f095b0'
  brandStrength: 0.1875
  lightness: 0.2606027435977012
  saturation: 0.8080827186349779
  rhythmicContrast: 0.026237464975565672
purpose: []
